apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: nezzo.narcizo@hotmail.com
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory # Endereco de quem vai responder o certificado
    solvers:
      - dns01:
          route53: # Fara verificacao diretamente no Route53 para criacao do certificado
            region: us-east-1
            hostedZoneID: Z07649571AQ3H5YSY0ZNM
