---
- hosts: database
  pre_tasks:
    - name: 'Atualiza o repositório apt-get e cache'
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: yes

    - name: 'Instalando as bibliotecas python-3 mysql'
      apt:
        name: ['python3-mysqldb']
        state: present
      become: yes
 
  tasks:
    - name: 'Instala pacotes de dependência do Sistema Operacional'
      apt: 
        name: ['mysql-server-8.0', 'unzip']
        state: latest
      become: yes
  
    - name: 'Cria banco de dados MySQL'
      mysql_db:
        name: wordpress_db
        login_user: root
        state: present
      become: yes

    - name: 'Cria usuário do Banco de Dados com nome wordpress_user e senha 12345 com todos os privilégios'
      mysql_user:
        name: wordpress_user
        password: '12345'
        priv: 'wordpress_db.*:ALL'
        state: present
        update_password: always
      become: yes


- hosts: wordpress
  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
      become: yes    

  tasks:
    - name: 'Instala todos os pacotes de dependências do Sistema Operacional' 
      apt: 
        name: ['php7.4', 'apache2', 'libapache2-mod-php7.4', 'php7.4-gd', 'php7.4-mysql', 'unzip']
        state: latest
      become: yes

    - name: 'Baixa o arquivo de instalação do Wordpress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
      become: yes
        
    - name: 'Descompactar o arquivo'
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/wordpress
        remote_src: yes
      become: yes

    - name: 'Cria uma cópia do arquivo wp-config-sample.php para não perdermos o exemplo'
      copy:
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes

    - name: 'Configura o wp-config com as entradas do banco de dados'
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: '{{ item.regex }}'
        replace: '{{ item.value }}'
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db'}
        - { regex: 'username_here', value: 'wordpress_user'}
        - { regex: 'password_here', value: '12345'}
        - { regex: 'localhost', value: '192.168.0.3'}    
      become: yes

    - name: 'Configura Apache (Colando o arquivo alterado) para servir o Wordpress'
      copy:
        src: './files/000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - Restart Apache

