# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "database"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
  end

  config.vm.define "database" do |db|
    db.vm.network "private_network", ip: "192.168.0.3"
  end

end
