apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts: # Criação do volume no container da mesma forma que fizemos antes
        - mountPath: /volume-dentro-do-container
          name: primeiro-pv
  volumes: # Criando o bind entre o PVC e o POD
    - name: primeiro-pv
      persistentVolumeClaim:
        claimName: pvc-1